report_comment: >
  For information about how to interpret these results, please see [ADD LINK HERE]
data_format: "yaml"
module_order:
  - cutadapt:
          name: "Cutadapt (trimmed)"
          info: "This section of the report shows the length of trimmed reads by Cutadapt for individual libraries."
  - fastqc:
          name: "FastQC (trimmed)"
          info: "This section of the report shows FastQC results after adapter trimming for individual libraries."
          path_filters: "fastqc_*.trimmed/*.zip"
  - fastqc:
          name: "FastQC (raw)"
          info: "This section of the report shows FastQC results before adapter trimming for individual libraries."
          path_filters: "fastqc_*/*.zip"
  - star 
  - picard:
          name: "Picard Mark Duplicates (Target Genome)"
          info: "This section of the report shows picard mark duplicate results after adapter trimming"
  - rseqc
