report_header_info:
  - Application Type: "RNA-seq"
data_format: "yaml"
skip_generalstats: true
module_order:
  - fastqc:
        name: "FastQC (raw)"
        info: "This section of the report shows FastQC results before adapter trimming for individual libraries."
        anchor: "fastqc_raw"
        path_filters_exclude: "*trimmed*"
  - fastqc:
        name: "FastQC (trimmed)"
        info: "This section of the report shows FastQC results after adapter trimming for individual libraries."
        anchor: "fastqc_trimmed"
        path_filters: "*trimmed*"

report_section_order:
  fastqc_trimmed:
    before: fastqc_raw